### ISSUE TITLE
Transparent Background

### ISSUE THREAD

**Issue by haideralipunjabi** [falahati/CircularProgressBar#3]
I can't set Transparent Background to the Circular Progress Bar

**Comment by falahati** [comment]
This control doesn't support transparent color for anti aliasing reasons. But in WinForm, transparent is same as the background of the parent object, so you can just set it directly to the background color of the parent object.

**Comment by haideralipunjabi** [comment]
Well I had to use it on a background with a Gradient and not solid color.
I was able to do the transparent background, by adding it to your code and compiling it. It looks and works fine, except for the fact that we can't keep both background and inner color transparent at the same time

**Comment by falahati** [comment]
I don't remember the details exactly but I think that it was about nonavailability of anti aliasing when clearing a part of drawing. Happens when we want to clean the inner circle before drawing more.
And as we need to draw something there to keep the background color and it wasn't acceptable to define two background property, I choose to not accept transparent at all.

http://gamedev.stackexchange.com/questions/13202/how-do-i-draw-anti-aliased-holes-in-a-bitmap

**Comment by falahati** [comment]
#6
