### ISSUE TITLE
Xamarin.Forms version?

### ISSUE THREAD

**Issue by alexrainman** [falahati/CircularProgressBar#4]
Have you think in migrate tis thing to a mobile platform?

**Comment by falahati** [comment]
Well this project was intended for WinForm. Other platforms and especially mobile platforms are rich in this types of controls.
For example for Xamarin you can go with:
https://components.xamarin.com/view/radialprogress
or this (android):
https://github.com/jamesmontemagno/MonoDroidToolkit/wiki/HoloCircularProgressBar

**Comment by alexrainman** [comment]
Well, if i am asking its because i did my research. The first one you mention? I implemented the abstractions for Xamarin.Forms and, it has its limitations, for example u cannot change the color of background circles, tha label in the center has a big fixed size. The second one by James is only for Android. I am planning to use it and add the iOS version, but yours? Its really reach component and it seems to be really flexible. Mobile is the thing now. Dont you think?

**Comment by alexrainman** [comment]
Thats why MS acquired Xamarin, thats why they are investing a lot in XForms because its xaml and it supports UWP that is the future of Windows. I may say that WinForm is dead already.

**Comment by falahati** [comment]
Lets don't go that far. WinForm is old-school, sure; dead? no. For simple tools requiring a UI, I go with WinForm 8 times out of 10 times.
But sure UWP and XAML are the way to go for Windows apps.

All these things aside,
1. I wrote this custom control to make an old WinForm program used in multiple platforms (Mono) kinda sexy. At the time, XAML was a nogo for its incompatibility with Mono.
2. Porting this thing is not practical. I didn't wrote any thing with Xamarin since 2014-2015 but I am sure even writing a new control for Xamarin and with multi platform support requires binding definitions, multi platform rendering, property listening, and so many time consuming optimizations for each platform.
3. I simply have no time to do so.

So if there is no good thing for Xamarin.Forms yet, well, how about writing one your-self? I would appreciate some good multi-platform Xamarin progress bar control. I am sure other do as well.

Thank you,

**Comment by alexrainman** [comment]
It was just a suggestion. Thanks anyway.

**Comment by falahati** [comment]
Sorry for disappointment. But you know, majority of the projects on github are just result of a personal or commercial unanswered need, that got shared for everyone to use.
